(() => {
  const body = document.body, isTtf = body.dataset.demo === "ttf", $ = (selector) => document.querySelector(selector);
  const dom = { scene: $("#scene"), step: $("#step"), label: $("#step-label"), gate: $("#gate"), psig: $("#psig"), logical: $("#logical"), phase: $("#phase"), coherence: $("#coherence"), protected: $("#protected"), route: $("#route"), support: $("#support"), activation: $("#activation"), play: $("#play"), reset: $("#reset"), baseline: $("#baseline"), regularized: $("#regularized") };
  const numeric = (value, digits = 3) => Number(value ?? 0).toFixed(digits);
  const snapshots = window.RATISS_DEMO_SNAPSHOTS, model = window.QuantumStudioModel;
  if (!snapshots) throw new Error("Snapshot WebGL absent.");
  if (!model) throw new Error("Modèle Quantum Studio absent.");
  const circuit = model.createDemoCircuit();
  let active = isTtf ? "baseline" : "trajectory", index = 0, playing = true, last = 0, drag = null;
  const current = () => isTtf ? snapshots.ttf[active] : snapshots.trajectory;
  const scene = new THREE.Scene(), camera = new THREE.PerspectiveCamera(40, 1, .1, 100), renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
  scene.fog = new THREE.FogExp2(0x061018, .045);
  const world = new THREE.Group(), graph = new THREE.Group(), logical = new THREE.Group(), field = new THREE.Group();
  world.add(graph, logical, field); scene.add(world); scene.add(new THREE.HemisphereLight(0xc5fbff, 0x07101b, 1.45));
  const key = new THREE.DirectionalLight(0x8fe7ff, 1.55); key.position.set(3.4, 4.5, 7.2); scene.add(key);
  const phaseLight = new THREE.PointLight(0xb99aff, 1.25, 11); phaseLight.position.set(-2.6, 1.6, 3.2); scene.add(phaseLight);
  camera.position.set(0, .35, 8.7); renderer.setPixelRatio(Math.min(devicePixelRatio, 2)); dom.scene.append(renderer.domElement);
  function resize(){const r=dom.scene.getBoundingClientRect();camera.aspect=r.width/r.height;camera.updateProjectionMatrix();renderer.setSize(r.width,r.height,false)}new ResizeObserver(resize).observe(dom.scene);resize();
  function renderDesign(){const ns="http://www.w3.org/2000/svg",svg=$("#design-schematic"),colors={qubit:"#4ce0c1",coupler:"#b99aff",resonator:"#79b7ff",feedline:"#f6c665",flux:"#f49de0"};$("#design-name").textContent=circuit.name;$("#component-count").textContent=`${circuit.nodes.length} / ${circuit.edges.length}`;$("#design-status").textContent="file:// prêt";for(const [s,t] of circuit.edges){const a=circuit.nodes.find(n=>n.id===s),b=circuit.nodes.find(n=>n.id===t),l=document.createElementNS(ns,"line");l.setAttribute("x1",a.x);l.setAttribute("y1",a.y);l.setAttribute("x2",b.x);l.setAttribute("y2",b.y);l.setAttribute("stroke","#62889b");l.setAttribute("stroke-width","1.35");svg.append(l)}for(const n of circuit.nodes){const g=document.createElementNS(ns,"g"),c=document.createElementNS(ns,"circle"),label=document.createElementNS(ns,"text"),f=document.createElementNS(ns,"text");c.setAttribute("cx",n.x);c.setAttribute("cy",n.y);c.setAttribute("r",n.kind==="qubit"?7:5.6);c.setAttribute("fill",colors[n.kind]||"#9fb6c1");c.setAttribute("stroke","#f5ffff");c.setAttribute("stroke-opacity",".65");label.setAttribute("x",n.x);label.setAttribute("y",n.y+1.5);label.setAttribute("text-anchor","middle");label.setAttribute("font-size","3.3");label.setAttribute("font-weight","700");label.setAttribute("fill","#061018");label.textContent=n.id;f.setAttribute("x",n.x);f.setAttribute("y",n.y+10);f.setAttribute("text-anchor","middle");f.setAttribute("font-size","2.4");f.setAttribute("fill","#c9e1e8");f.textContent=`${n.frequency} ${n.unit}`;g.append(c,label,f);svg.append(g)}const kinds={qubit:"josephson",coupler:"metal",resonator:"resonator",feedline:"control",flux:"control"},counts={};circuit.nodes.forEach(n=>counts[kinds[n.kind]||"control"]=(counts[kinds[n.kind]||"control"]||0)+1);$("#design-layers").innerHTML=Object.entries(counts).map(([name,total])=>`<div class="mini-row violet"><b>${name}</b> · ${total} proxy(s)</div>`).join("");const qs=circuit.nodes.filter(n=>n.kind==="qubit"),delta=Math.abs(qs[0].frequency-qs[1].frequency);$("#design-frequency").innerHTML=qs.map((n,i)=>`<div class="mini-row"><b>${n.id}</b> · ${n.frequency} GHz<br>voisin ${qs[1-i].id} · Δ ${delta.toFixed(3)} GHz · stable</div>`).join("");const risk=model.crosstalkRiskAnalysis(circuit)[0];$("#design-crosstalk").innerHTML=`<div class="mini-row gold"><b>${risk.first} ↔ ${risk.second}</b> · ${risk.score}/100<br>${risk.couplingPaths.join(", ")} · Δ ${Number(risk.detuning).toFixed(3)} GHz · overlay nominal</div>`;$("#design-console").textContent=JSON.stringify({runtime:"file://",design:circuit.name,snapshot:isTtf?"ttf_smooth_ablation":"studio_transmon_microcell_timeline",sidecar:"RATISS TopologicalQubit · phase / twist / coherence",network:"not required"},null,2)}
  function dispose(layer){while(layer.children.length){const child=layer.children[0];layer.remove(child);child.traverse(o=>{o.geometry?.dispose?.();(Array.isArray(o.material)?o.material:[o.material]).filter(Boolean).forEach(m=>m.dispose?.())})}}
  function line(parent,pts,color,dashed=false,opacity=.82){if(pts.length<2)return;const g=new THREE.BufferGeometry().setFromPoints(pts),m=dashed?new THREE.LineDashedMaterial({color,dashSize:.13,gapSize:.09,transparent:true,opacity}):new THREE.LineBasicMaterial({color,transparent:true,opacity}),l=new THREE.Line(g,m);if(dashed)l.computeLineDistances();parent.add(l)}
  function ringPoint(a,twist){const f=twist/Math.PI,r=1.62+f*.34*Math.sin(3*a);return new THREE.Vector3(r*Math.cos(a),r*Math.sin(a),f*.36*Math.cos(3*a))}
  function addField(){const pts=[];for(let i=0;i<90;i++){const a=i*2.3999632297,r=2.45+(i%9)*.06;pts.push(new THREE.Vector3(Math.cos(a)*r,Math.sin(a)*r,-1.4-(i%5)*.06))}field.add(new THREE.Points(new THREE.BufferGeometry().setFromPoints(pts),new THREE.PointsMaterial({color:0x79b7ff,size:.025,transparent:true,opacity:.36})))}
  function addGraph(step){const byId=new Map((step.qubits||[]).map(n=>[n.id,n]));for(const e of step.edges||[]){const a=byId.get(e.source),b=byId.get(e.target);if(!a||!b)continue;const from=new THREE.Vector3(...a.position),to=new THREE.Vector3(...b.position),mid=from.clone().add(to).multiplyScalar(.5);const c=Math.max(0,Number(e.correlation??e.mutual_information??0)),stable=Math.max(0,Math.min(1,Number(e.stability??1)));mid.y+=.34+c*.95;mid.z+=e.type==="quantum_candidate"?.42:.14;const color=e.type==="quantum_candidate"?0x4ce0c1:0x79b7ff;graph.add(new THREE.Mesh(new THREE.TubeGeometry(new THREE.QuadraticBezierCurve3(from,mid,to),36,.012+c*.058,7,false),new THREE.MeshStandardMaterial({color,emissive:color,emissiveIntensity:.22+c*.5,transparent:true,opacity:.2+stable*.78,roughness:.27,metalness:.28})))}const route=step.tsp_inspection?.path||[];line(graph,route.map(id=>byId.get(id)).filter(Boolean).map(n=>new THREE.Vector3(...n.position)),0xf2abff,true,.96);for(const n of step.qubits||[]){const critical=Number(n.criticality||0)>=.38,support=Math.max(0,Number(n.topology_support||0)),size=.13+support*.28,color=critical?0xff687a:0x57d4bf,mesh=new THREE.Mesh(new THREE.IcosahedronGeometry(size,3),new THREE.MeshStandardMaterial({color,emissive:color,emissiveIntensity:critical?.42:.24+support*.22,roughness:.25,metalness:.26}));mesh.position.set(...n.position);graph.add(mesh);const aura=new THREE.Mesh(new THREE.SphereGeometry(size*(critical?2.15:1.55),18,12),new THREE.MeshBasicMaterial({color,transparent:true,opacity:critical?.09:.045,wireframe:true}));aura.position.copy(mesh.position);graph.add(aura)}}
  function addLogical(state){if(!state||state.P_sig==null||!Number.isFinite(Number(state.P_sig)))return;const phase=Number(state.phase||0),twist=Number(state.twist||0),coh=Math.max(0,Math.min(1,Number(state.coherence??1))),sig=Math.max(0,Number(state.P_sig||0)),safe=Boolean(state.protected),color=safe?0x4ce0c1:0xff687a;logical.rotation.set(0,0,phase);logical.userData.coherence=coh;const points=Array.from({length:97},(_,i)=>ringPoint(Math.PI*2*i/96,twist)),curve=new THREE.CatmullRomCurve3(points,true,"centripetal");logical.add(new THREE.Mesh(new THREE.TubeGeometry(curve,144,.034+Math.min(sig,1.5)*.026,9,true),new THREE.MeshStandardMaterial({color,emissive:color,emissiveIntensity:.32+coh*.54,transparent:true,opacity:.28+coh*.7,roughness:.21,metalness:.34})));[0xb99aff,0xfa9cde,0x79b7ff].forEach((c,k)=>{const p=Array.from({length:121},(_,i)=>{const a=Math.PI*2*i/120,b=ringPoint(a,twist),r=.15*Math.sin(3*a+k*Math.PI*2/3);b.x+=r*Math.cos(a);b.y+=r*Math.sin(a);b.z+=.14*Math.cos(3*a+k*Math.PI*2/3);return b});logical.add(new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(p,true,"centripetal"),156,.015,6,true),new THREE.MeshStandardMaterial({color:c,emissive:c,emissiveIntensity:.3+coh*.22,transparent:true,opacity:.34+coh*.4,roughness:.32})))});for(let i=0;i<12;i++){const bead=new THREE.Mesh(new THREE.SphereGeometry(.055+sig*.014,14,10),new THREE.MeshStandardMaterial({color:0xe6fffa,emissive:color,emissiveIntensity:.62,roughness:.18}));bead.position.copy(ringPoint(Math.PI*2*i/12,twist));logical.add(bead)}const extent=Math.max(.18,Math.min(Math.PI*2,phase||.18)),arc=Array.from({length:32},(_,i)=>{const a=-Math.PI/2+extent*i/31;return new THREE.Vector3(2.15*Math.cos(a),2.15*Math.sin(a),.15)});line(logical,arc,0xf6c665,false,.92);const arrow=new THREE.Mesh(new THREE.ConeGeometry(.075,.19,12),new THREE.MeshStandardMaterial({color:0xf6c665,emissive:0xf6c665,emissiveIntensity:.7}));arrow.position.copy(arc.at(-1));arrow.rotation.z=Math.PI/2+(-Math.PI/2+extent);logical.add(arrow)}
  function update(step,state){const has=state?.P_sig!=null&&Number.isFinite(Number(state.P_sig)),scope=step.ttf_smooth_ablation;dom.label.textContent=`${current().provenance?.mode||"local"} · étape ${step.step} / ${(current().steps||[]).length-1} · ${has?"qubit topologique logiciel":"graphe d’inspection"}`;dom.gate.textContent=scope?`${step.gate} · frontière [${(scope.boundary_nodes||[]).join(", ")}]`:step.gate;dom.psig.textContent=numeric(step.topology?.psig);dom.logical&&(dom.logical.textContent=has?numeric(state.P_sig):"—");dom.phase&&(dom.phase.textContent=has?`${numeric(state.phase)} / ${numeric(state.twist)} rad`:"non exportée");dom.coherence&&(dom.coherence.textContent=has?numeric(state.coherence):"non exportée");if(dom.protected){dom.protected.textContent=has?(state.protected?`oui · bit ${state.logical_bit}`:`non · bit ${state.logical_bit}`):"non exporté";dom.protected.style.color=state?.protected?"#82f4dc":"#ff99a5"}dom.route&&(dom.route.textContent=(step.tsp_inspection?.path||[]).length?step.tsp_inspection.path.join(" → "):"Aucune");dom.support&&(dom.support.textContent=numeric((step.qubits||[]).reduce((s,n)=>s+Number(n.topology_support||0),0)));dom.activation&&(dom.activation.textContent=scope?.activation?numeric(scope.activation.reduce((s,v)=>s+v,0)/scope.activation.length):"—");dom.step.max=Math.max(0,(current().steps||[]).length-1);dom.step.value=index}
  function draw(){const step=(current().steps||[])[index]||current().steps?.[0];if(!step)return;dispose(graph);dispose(logical);dispose(field);addField();addGraph(step);addLogical(step.logical_topology);update(step,step.logical_topology)}
  function scenario(name){active=name;index=0;dom.baseline?.classList.toggle("active",name==="baseline");dom.regularized?.classList.toggle("active",name==="regularized");draw()}dom.step.addEventListener("input",()=>{index=Number(dom.step.value);draw()});dom.play.addEventListener("click",()=>{playing=!playing;dom.play.textContent=playing?"Pause":"Lire"});dom.reset?.addEventListener("click",()=>{camera.position.set(0,.35,8.7);world.rotation.set(0,0,0)});dom.baseline?.addEventListener("click",()=>scenario("baseline"));dom.regularized?.addEventListener("click",()=>scenario("regularized"));dom.scene.addEventListener("pointerdown",e=>drag={x:e.clientX,y:e.clientY});addEventListener("pointerup",()=>drag=null);addEventListener("pointermove",e=>{if(!drag)return;world.rotation.y+=(e.clientX-drag.x)*.008;world.rotation.x+=(e.clientY-drag.y)*.008;drag={x:e.clientX,y:e.clientY}});dom.scene.addEventListener("wheel",e=>{camera.position.z=Math.max(4.3,Math.min(18,camera.position.z+e.deltaY*.01))},{passive:true});function animate(t){requestAnimationFrame(animate);if(playing&&t-last>1600){last=t;index=(index+1)%Math.max(1,(current().steps||[]).length);draw()}if(!drag){world.rotation.y+=.00075;logical.rotation.y+=.0014*(logical.userData.coherence??1)}field.rotation.z-=.00045;renderer.render(scene,camera)}renderDesign();draw();requestAnimationFrame(animate);
})();
